
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SinFlexSinema.DB
{

using System;
    using System.Collections.Generic;
    
public partial class Bilet
{

    public int Bilet_ID { get; set; }

    public int Film_ID { get; set; }

    public int Salon_ID { get; set; }

    public byte KoltukNumarasi { get; set; }

    public int Satis_ID { get; set; }

    public int Musteri_ID { get; set; }



    public virtual Film Film { get; set; }

    public virtual Salon Salon { get; set; }

    public virtual Sati Sati { get; set; }

}

}
