
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SinFlexSinema.DB
{

using System;
    using System.Collections.Generic;
    
public partial class Rezervasyon
{

    public int Rezervasyon_ID { get; set; }

    public int Salon_ID { get; set; }

    public int Seans_ID { get; set; }

    public string RezervasyonNo { get; set; }

    public string Durumu { get; set; }

    public Nullable<decimal> Fiyat { get; set; }



    public virtual Salon Salon { get; set; }

    public virtual Sean Sean { get; set; }

}

}
