
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SinFlexSinema.DB
{

using System;
    using System.Collections.Generic;
    
public partial class Salon
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Salon()
    {

        this.Bilets = new HashSet<Bilet>();

        this.Rezervasyons = new HashSet<Rezervasyon>();

    }


    public int Salon_ID { get; set; }

    public string Adi { get; set; }

    public byte Kapasite { get; set; }

    public string SiraSayisi { get; set; }

    public int Seans_ID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Bilet> Bilets { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rezervasyon> Rezervasyons { get; set; }

    public virtual Sean Sean { get; set; }

}

}
