
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SinFlexSinema.DB
{

using System;
    using System.Collections.Generic;
    
public partial class Sati
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sati()
    {

        this.Bilets = new HashSet<Bilet>();

    }


    public int Satis_ID { get; set; }

    public System.DateTime Tarih { get; set; }

    public decimal Fiyat { get; set; }

    public int SatisTur_ID { get; set; }

    public float İndirim { get; set; }

    public int Kampanya_ID { get; set; }

    public int User_ID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Bilet> Bilets { get; set; }

    public virtual Kampanya Kampanya { get; set; }

    public virtual SatisTur SatisTur { get; set; }

    public virtual User User { get; set; }

}

}
