
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SinFlexSinema.DB
{

using System;
    using System.Collections.Generic;
    
public partial class Sean
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sean()
    {

        this.Rezervasyons = new HashSet<Rezervasyon>();

        this.Salons = new HashSet<Salon>();

    }


    public int Seans_ID { get; set; }

    public string Seans_Baslama_Saati { get; set; }

    public System.TimeSpan Seans_Bitis_Saati { get; set; }

    public int Film_ID { get; set; }



    public virtual Film Film { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rezervasyon> Rezervasyons { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Salon> Salons { get; set; }

}

}
