
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SinFlexSinema.DB
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.Satis = new HashSet<Sati>();

    }


    public int User_ID { get; set; }

    public string KullaniciAdi { get; set; }

    public string Sifre { get; set; }

    public string Aciklama { get; set; }

    public Nullable<byte> Yas { get; set; }

    public Nullable<bool> Cinsiyet { get; set; }

    public string Meslek { get; set; }

    public string Email { get; set; }

    public string Adi { get; set; }

    public string Soyadi { get; set; }

    public Nullable<System.DateTime> DogumTarihi { get; set; }

    public string TcKimlikNo { get; set; }

    public Nullable<System.DateTime> KayitTarihi { get; set; }

    public Nullable<int> UserTypeId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sati> Satis { get; set; }

    public virtual UserType UserType { get; set; }

}

}
